title: Juicy Offsec
description: "Xinyue's Security Blog"
author:
  name: "Xinyue"
  email: "gtxxxy@gmail.com"
  url: "https://xxxinhy.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Xinyue"
year : "2024"
